# Generated by Django 4.0.1 on 2023-05-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_event_host_alter_event_category_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(max_length=255, verbose_name='host name'),
        ),
    ]
