# Generated by Django 4.0.10 on 2023-06-10 08:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_servicecontent_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='service_content',
            field=tinymce.models.HTMLField(default='*'),
        ),
    ]
