# Generated by Django 4.0.10 on 2023-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contactrequest_site_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(default='_ no description _', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo'),
        ),
        migrations.AddField(
            model_name='site',
            name='tagline',
            field=models.CharField(default='_ no tagline _', max_length=255),
        ),
    ]
