# Generated by Django 4.0.10 on 2023-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_site_description_site_logo_site_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='_ no name _', max_length=255)),
                ('description', models.CharField(default='_ no description _', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/partner/logo')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='favico',
            field=models.ImageField(blank=True, null=True, upload_to='site/favico'),
        ),
    ]
