# Generated by Django 4.0.10 on 2023-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sitepartner_site_favico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='site/partner/logo')),
            ],
        ),
        migrations.AddField(
            model_name='sitepartner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitepartner',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitepartner',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
