# Generated by Django 3.2.19 on 2023-06-20 13:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_sitetestimonial_sitepartner_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='home/'),
        ),
        migrations.AddField(
            model_name='site',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='home/'),
        ),
        migrations.AddField(
            model_name='site',
            name='about_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='home/'),
        ),
        migrations.AddField(
            model_name='site',
            name='about_short_discription',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='about_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='blog_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='event_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='gallery_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='service_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
