# Generated by Django 3.2.19 on 2023-06-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20230620_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='about_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
