# Generated by Django 3.2.19 on 2023-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20230620_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='divider_logo_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_logo_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_logo_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_logo_4',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_short_discription_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_short_discription_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_short_discription_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_short_discription_4',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_title_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_title_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_title_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='divider_title_4',
        ),
    ]
