# Generated by Django 3.2.19 on 2023-06-20 15:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20230620_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.CharField(max_length=255)),
                ('image_2', models.CharField(max_length=255)),
                ('image_3', models.CharField(max_length=255)),
                ('short_description', tinymce.models.HTMLField()),
                ('description', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='books/images/posts'),
            preserve_default=False,
        ),
    ]
