# Generated by Django 3.2.19 on 2023-06-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20230620_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutussection',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
