# Generated by Django 3.2.19 on 2023-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20230620_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='blog_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='event_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='gallery_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='service_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
