# Generated by Django 3.2.19 on 2023-06-20 15:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20230620_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('service_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('gallery_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('blog_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('contact_background', models.ImageField(blank=True, null=True, upload_to='background/')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='about_short_discription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
