# Generated by Django 3.2.19 on 2023-06-20 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20230620_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
