# Generated by Django 4.0.1 on 2023-05-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestgroup',
            name='another_auto_field',
        ),
        migrations.AlterField(
            model_name='guestgroup',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
