# Generated by Django 4.0.1 on 2023-05-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_guestgroup_another_auto_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationletter',
            old_name='invitation_number',
            new_name='total_invitation',
        ),
        migrations.AlterField(
            model_name='guestgroup',
            name='sequence',
            field=models.IntegerField(blank=True),
        ),
    ]
