# Generated by Django 4.0.1 on 2023-05-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_invitationletter_invitation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationletter',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admins.guestgroup'),
        ),
    ]
