# Generated by Django 4.0.1 on 2023-05-31 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_invitationletter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationletter',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_set', to='admins.guestgroup'),
        ),
    ]
