# Generated by Django 4.0.1 on 2023-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_guesttable_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='attachment',
            field=models.FileField(blank=True, help_text='File Should be less than 5mb', null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
