# Generated by Django 4.0.1 on 2023-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_table_created_at_table_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationletter',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='invitationletter',
            name='sequence',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
