# Generated by Django 4.0.10 on 2023-06-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_provider_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created_at']},
        ),
    ]
